# Generated by Django 4.2.29 on 2026-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_empreendedor', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('segmento', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('comercio', 'Comércio'), ('industria', 'Indústria'), ('servicos', 'Serviços'), ('agronegocio', 'Agronegócio')], max_length=20)),
                ('contato', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
